baseurl = "https://ifm2019.hvl.no"
title = "ICTAC 2020"
canonifyurls = true
paginate = 10
theme = "ictac-theme"
themesDir = "."
languageCode = "en-us"
copyright = "ICTAC 2020"
relativeURLs = true #CESAR

[author]
    name = "iFM'19"

[params]
  DateForm = "Mon, 2 Jan, 2006"
  Description = "17th International Colloquium on Theoretical Aspects of Computing"
  Author = "ICTAC 2020"
  Venue = "Macau S.A.R., China"
  email = "ictac2020@easychair.org"
  date = "30 Nov - 4 Dec 2020"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  customCSS = ["/css/custom.css"]

#[[menu.main]]
#  name = "home"
#  url = "/"
#  weight = -200
[[menu.main]]
  name = "committees"
  url = "/committees"
  weight = 15  
[[menu.main]]
  identifier = "practicalinfo"
  name = "Participation"
  url = "/"
  weight = 50
#[[menu.main]]
#  parent = 'practicalinfo'
#  name = "dates"
#  url = "/dates"
#  weight = 51
[[menu.main]]
    parent = 'practicalinfo'
    name = "Venue"
    url  = "/venue"
    weight = 52  
#[[menu.main]]
#    parent = 'practicalinfo'
#    name = "Accommodation"
#    url  = "/accommodation"
#    weight = 53  
#[[menu.main]]
#    parent = 'practicalinfo'
#    name = "Getting there"
#    url  = "/gettingthere"
#    weight = 54
#[[menu.main]]
#    parent = 'practicalinfo'
#    name = "Social Events"
#    url  = "/social"
#    weight = 55    
#[[menu.main]]
#  parent = 'practicalinfo'
#  name = "Contact"
#  url = "/contact"
#  weight = 200  
#[[menu.main]]
#    identifier = "calls"
#    name = "calls"
#    url = "/"
#    weight = 10
[[menu.main]]
#    parent = 'calls'
    name = "Call for Papers"
    url  = "/cfp"
    weight = 12    
#[[menu.main]]
#    parent = 'calls'
#    name = "Call for Workshops and Tutorials"
#    url  = "/cfwt"
#    weight = 16
#[[menu.main]]
#    identifier = "colocated"
#    name = "Co-located Events"
#    url = "/"
#    weight = "20"
#[[menu.main]]
#    parent = 'colocated'
#    name = "PhD Symposium"
#    url = "/phd-symposium"
#    weight = "21"
#[[menu.main]]
#    parent = 'colocated'
#    name = "FMFun 2019"
#    url = "/fmfun"
#    weight = "22"
#[[menu.main]]
#    parent = 'colocated'
#    name = "FMAIL 2019"
#    url = "/fmail"
#    weight = "23"
#[[menu.main]]
#    parent = 'colocated'
#    name = "COEMS workshop"
#    url = "https://www.coems.eu/dissemination/coems-workshop-at-ifm-2019/"
#    weight = "24"
#[[menu.main]]
#    parent = 'colocated'
#    name = "Refactoring tutorials"
#    url = "/refa"
#    weight = "24"      
#[[menu.main]]
#  identifier = "programme"
#  name = "programme"
#  url = "/"
#  weight = 30
#[[menu.main]]
#    parent = 'programme'
#    name = "Keynote Speakers"
#    url  = "/keynotes"
#    weight = 31  
#[[menu.main]]
#    parent = 'programme'
#    name = "Accepted Papers"
#    url  = "/accepted"
#    weight = 32
#[[menu.main]]
#    parent = 'programme'
#    name = "Detailed Schedule"
#    url = "https://easychair.org/smart-program/iFM2019/"
#    weight = "34"
#[[menu.main]]
#    parent = 'programme'
#    name = "Schedule Overview"
#    url  = "/registration/#pp"
#    weight = 33    
#[[menu.main]]
#  name = "registration"
#  url = "/registration"
#  weight = 60
